baseURL = 'https://axelfoley85.github.io/vs-rpg-berlin/'
languageCode = 'en-us'
title = "VS RPG Berlin"
theme = "ananke"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  favicon = "/img/favicon.ico"
  